font_family        Mononoki Nerd Font
font_size 17.0
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 Symbols Nerd Font Mono

scrollbar_handle_color #c7c7c7

url_color #0087bd
url_style straight

tab_bar_style powerline
tab_powerline_style angled

active_tab_foreground   #e1e1e1
active_tab_background   #454545
active_tab_font_style   bold
inactive_tab_foreground #c7c7c7
inactive_tab_background #454545
inactive_tab_font_style normal

background #343434
foreground #b2b2b2
selection_background #454545
selection_foreground #e1e1e1
background_opacity 1.0


#: black

 color0 #000000
 color8 #000000

#: red

 color1 #404040
 color9 #404040

#: green

 color2  #454545
 color10 #454545

#: yellow

 color3  #858585
 color11 #858585

#: blue

 color4  #b2b2b2
 color12 #b2b2b2

#: magenta

 color5  #c7c7c7
 color13 #c7c7c7

#: cyan

 color6  #e1e1e1
 color14 #e1e1e1

#: white

 color7  #f3f3f3
 color15 #ffffff
