xwayland {
    enabled = true
    force_zero_scaling = true
}

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:class com.github.wwmm.easyeffects

windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:class via-nativia

windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:class unityhub

windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:class Spotify

windowrule = float on,match:class nm-connection-editor
windowrule = size 35% 30%,match:class nm-connection-editor

# TODO: add this back
windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:class floating-kitty

windowrule = float on, center on, size (monitor_w*0.5) (monitor_h*0.5), match:class small-floating-kitty

windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:title yazi

windowrule = float on, center on, size (monitor_w*0.6) (monitor_h*0.7), match:class org.gnome.Nautilus

layerrule = blur on, match:namespace logout_dialog
layerrule = xray off, match:namespace logout_dialog

layerrule = animation slide right, match:namespace swaync-control-center

layerrule = no_anim on, match:namespace hyprpaper
layerrule = no_anim on, match:namespace hyprpicker
layerrule = animation fade, match:namespace logout_dialog
layerrule = animation fade, match:namespace quickshell
