$wallp_1 = awww img ~/.config/wallpapers/inabakumori_wallpaper_1.webp --transition-fps 255 --transition-step 10 -o DP-1
$wallp_2 = awww img ~/.config/wallpapers/inabakumori_wallpaper_2.png --transition-fps 255 --transition-step 10 -o HDMI-A-1
$wallp_3 = awww img ~/.config/wallpapers/inabakumori_wallpaper_3.png --transition-fps 255 --transition-step 10 -o DP-3
$wallp_4 = awww img ~/.config/wallpapers/inabakumori_wallpaper_4.png --transition-fps 255 --transition-step 10 -o DP-1
$wallp_5 = awww img ~/.config/wallpapers/inabakumori_wallpaper_5.png --transition-fps 255 --transition-step 10 -o DP-3
$wallp_6 = awww img ~/.config/wallpapers/inabakumori_wallpaper_6.jpg --transition-fps 255 --transition-step 10 -o HDMI-A-1
